//! Compiles the version 1 conformance corpus into this crate.
//!
//! `conformance/v1` lives outside `crates/ethogram` (two levels up from
//! `CARGO_MANIFEST_DIR`), so this script — and the accessor it feeds,
//! `ethogram::v1_fixtures()` — depends on the repository layout around the
//! crate. That is fine for a git dependency, a path dependency, and the
//! vendored tree, which is every way this crate is consumed today (it is
//! never published: `publish = false`, and onsager-ai/ethogram#10 records
//! why). It would break a crates.io publish, where files outside the package
//! root are not included in the uploaded package; a first publish would need
//! either an `include` list reaching outside the crate or the fixtures moved
//! inside it.
//!
//! There is deliberately no committed generated file. The crate this
//! replaced (`ethogram-corpus`, deleted in onsager-ai/ethogram#70 on a
//! "zero dependents" finding that was wrong — umwelt depends on it three
//! ways) committed its generated Rust and TypeScript views and policed drift
//! with a CI regeneration-and-diff check. Regenerating on every build removes
//! that failure mode instead of guarding it: there is nothing committed to
//! drift.
//!
//! A missing or unreadable corpus directory, or an empty one, fails the
//! build outright rather than compiling in a silently empty or short array —
//! that would make every downstream assertion that reads `v1_fixtures()`
//! vacuously pass.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"));
    let corpus_dir = manifest_dir.join("../../conformance/v1");

    // Rerun if the directory itself changes (a fixture added or removed) —
    // and, below, for each individual file, since directory-only
    // rerun-if-changed is not sufficient on all platforms to catch an edit
    // to a file already inside it.
    println!("cargo:rerun-if-changed={}", corpus_dir.display());

    let corpus_dir = corpus_dir.canonicalize().unwrap_or_else(|error| {
        panic!(
            "ethogram build script: cannot read the conformance corpus at {} ({error}). \
             This crate compiles in conformance/v1 from the repository layout around it \
             (see crates/ethogram/build.rs); a git dependency, a path dependency, or the \
             vendored tree must keep that directory reachable two levels above \
             CARGO_MANIFEST_DIR.",
            corpus_dir.display(),
        )
    });

    let read_dir = fs::read_dir(&corpus_dir).unwrap_or_else(|error| {
        panic!(
            "ethogram build script: cannot list the conformance corpus directory {} ({error})",
            corpus_dir.display(),
        )
    });

    let mut names = read_dir
        .map(|entry| {
            let entry = entry.unwrap_or_else(|error| {
                panic!(
                    "ethogram build script: cannot read an entry in {} ({error})",
                    corpus_dir.display(),
                )
            });
            entry.file_name()
        })
        .filter(|file_name| {
            let path = corpus_dir.join(file_name);
            path.is_file()
                && path
                    .extension()
                    .is_some_and(|extension| extension == "json")
        })
        .map(|file_name| {
            file_name
                .into_string()
                .unwrap_or_else(|raw| panic!("fixture file name {raw:?} is not valid UTF-8"))
        })
        .collect::<Vec<String>>();

    // UTF-8 byte order — the corpus's existing convention (see
    // `crates/ethogram/tests/corpus_inventory.rs` and the deleted
    // generator this replaces), not each platform's directory-listing order.
    names.sort_by(|left, right| left.as_bytes().cmp(right.as_bytes()));

    if names.is_empty() {
        panic!(
            "ethogram build script: no *.json fixtures found in {}. A silently empty \
             compiled-in corpus would make every assertion built on v1_fixtures() vacuous \
             rather than failing loudly.",
            corpus_dir.display(),
        );
    }

    let mut source = String::from(
        "// @generated by crates/ethogram/build.rs from conformance/v1; do not edit.\n\n\
         pub(crate) static V1_FIXTURES: &[Fixture] = &[\n",
    );

    for name in &names {
        let absolute_path = corpus_dir.join(name);
        // Emitted for every file, in addition to the directory above: an
        // edit to a fixture already listed (not merely an add or a remove)
        // must also trigger a rebuild.
        println!("cargo:rerun-if-changed={}", absolute_path.display());

        source.push_str(&format!(
            "    Fixture {{ name: {name:?}, raw_json: include_str!({path:?}) }},\n",
            name = name,
            path = absolute_path.display().to_string(),
        ));
    }

    source.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    fs::write(out_dir.join("corpus_fixtures.rs"), source).unwrap_or_else(|error| {
        panic!("ethogram build script: cannot write corpus_fixtures.rs ({error})")
    });
}
