[package]
name = "umwelt-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[example]]
name = "capture_interrupt"
test = true

[features]
conformance = []

[dependencies]
chrono.workspace = true
ethogram.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
umwelt-capture = { path = "../umwelt-capture" }

[lints]
workspace = true
