use std::{
    collections::{BTreeMap, BTreeSet},
    fs, io,
    path::{Path, PathBuf},
};

use ostrom_core::{PolicyManifest, ResolvedLoop, ResolvedLoopCeilings};
use thiserror::Error;

const GENERATED_HEADER: &str = "# Generated by `ostrom loops render`; do not edit.\n";
const UNIT_PREFIX: &str = "ostrom-loop-";
const RECONCILER_UNIT: &str = "ostrom-up.service";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoopUnit {
    pub name: String,
    pub contents: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoopUnitDrift {
    pub missing: Vec<String>,
    pub changed: Vec<String>,
    pub unexpected: Vec<String>,
}

impl LoopUnitDrift {
    #[must_use]
    pub fn is_clean(&self) -> bool {
        self.missing.is_empty() && self.changed.is_empty() && self.unexpected.is_empty()
    }
}

#[derive(Debug, Error)]
pub enum LoopUnitError {
    #[error("could not resolve loop `{name}`: {message}")]
    Resolve { name: String, message: String },
    #[error("could not create loop unit directory `{}`: {source}", path.display())]
    CreateDirectory {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("could not write loop unit `{}`: {source}", path.display())]
    Write {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("could not inspect loop unit directory `{}`: {source}", path.display())]
    Inspect {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("could not read loop unit `{}`: {source}", path.display())]
    Read {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
}

pub fn generate_loop_units(manifest: &PolicyManifest) -> Result<Vec<LoopUnit>, LoopUnitError> {
    let mut units = Vec::with_capacity(manifest.loops.len() * 2 + 1);
    if !manifest.loops.is_empty() {
        units.push(LoopUnit {
            name: RECONCILER_UNIT.to_owned(),
            contents: render_reconciler_service(),
        });
    }
    for name in manifest.loops.keys() {
        let resolved = manifest
            .resolve_loop(name)
            .map_err(|error| LoopUnitError::Resolve {
                name: name.clone(),
                message: error.to_string(),
            })?;
        units.push(LoopUnit {
            name: format!("{UNIT_PREFIX}{name}.service"),
            contents: render_service(&resolved),
        });
        units.push(LoopUnit {
            name: format!("{UNIT_PREFIX}{name}.timer"),
            contents: render_timer(&resolved),
        });
    }
    units.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(units)
}

/// Write generated unit files without enabling, starting, or reloading them.
pub fn render_loop_units(
    manifest: &PolicyManifest,
    output: &Path,
) -> Result<Vec<PathBuf>, LoopUnitError> {
    let units = generate_loop_units(manifest)?;
    fs::create_dir_all(output).map_err(|source| LoopUnitError::CreateDirectory {
        path: output.to_path_buf(),
        source,
    })?;
    let mut written = Vec::with_capacity(units.len());
    for unit in units {
        let path = output.join(unit.name);
        fs::write(&path, unit.contents).map_err(|source| LoopUnitError::Write {
            path: path.clone(),
            source,
        })?;
        written.push(path);
    }
    Ok(written)
}

pub fn check_loop_units_drift(
    manifest: &PolicyManifest,
    installed: &Path,
) -> Result<LoopUnitDrift, LoopUnitError> {
    let expected = generate_loop_units(manifest)?
        .into_iter()
        .map(|unit| (unit.name, unit.contents))
        .collect::<BTreeMap<_, _>>();
    let entries = fs::read_dir(installed).map_err(|source| LoopUnitError::Inspect {
        path: installed.to_path_buf(),
        source,
    })?;
    let mut actual_names = BTreeSet::new();
    let mut changed = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|source| LoopUnitError::Inspect {
            path: installed.to_path_buf(),
            source,
        })?;
        let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
            continue;
        };
        if !managed_unit_name(&name) {
            continue;
        }
        actual_names.insert(name.clone());
        if let Some(expected_contents) = expected.get(&name) {
            let path = entry.path();
            let actual =
                fs::read_to_string(&path).map_err(|source| LoopUnitError::Read { path, source })?;
            if &actual != expected_contents {
                changed.push(name);
            }
        }
    }
    let expected_names = expected.keys().cloned().collect::<BTreeSet<_>>();
    Ok(LoopUnitDrift {
        missing: expected_names.difference(&actual_names).cloned().collect(),
        changed,
        unexpected: actual_names.difference(&expected_names).cloned().collect(),
    })
}

/// Structural form of the security check retained from the handwritten units.
#[must_use]
pub fn loop_execstart_is_not_shell(units: &[LoopUnit]) -> bool {
    units
        .iter()
        .filter(|unit| unit.name.starts_with(UNIT_PREFIX) && unit.name.ends_with(".service"))
        .all(|unit| {
            let starts = unit
                .contents
                .lines()
                .filter_map(|line| line.strip_prefix("ExecStart="))
                .collect::<Vec<_>>();
            starts.len() == 1
                && starts[0].starts_with("ostrom loop run ")
                && !starts[0].contains([';', '|', '&', '$', '`'])
                && !starts[0].contains("sh -c")
        })
}

fn managed_unit_name(name: &str) -> bool {
    name == RECONCILER_UNIT
        || (name.starts_with(UNIT_PREFIX)
            && (name.ends_with(".service") || name.ends_with(".timer")))
}

fn render_reconciler_service() -> String {
    format!(
        "{GENERATED_HEADER}[Unit]\nDescription=Reconcile Ostrom loops from the current policy version\nWants=network-online.target\nAfter=network-online.target\n\n[Service]\nType=oneshot\nExecStart=ostrom up\n\n[Install]\nWantedBy=default.target\n"
    )
}

fn render_service(resolved: &ResolvedLoop) -> String {
    let mut source = String::new();
    source.push_str(GENERATED_HEADER);
    source.push_str("[Unit]\n");
    source.push_str(&format!("Description=Ostrom loop {}\n", resolved.name));
    source.push_str("Wants=network-online.target\nAfter=network-online.target\n\n");
    source.push_str("[Service]\nType=oneshot\n");
    source.push_str(&format!("Environment=OSTROM_ACTOR={}\n", resolved.actor));
    render_ceilings(&mut source, resolved.ceilings);
    source.push_str(&format!("ExecStart=ostrom loop run {}\n", resolved.name));
    source.push_str("TimeoutStartSec=1800\nKillMode=control-group\n");
    source
}

fn render_ceilings(source: &mut String, ceilings: ResolvedLoopCeilings) {
    if let Some(value) = ceilings.spend_usd {
        source.push_str(&format!(
            "Environment=MANDATE_DAILY_CAP_USD={}\n",
            render_number(value)
        ));
    }
    if let Some(value) = ceilings.concurrent {
        source.push_str(&format!("Environment=MANDATE_MAX_IMPLEMENTERS={value}\n"));
    }
    if let Some(value) = ceilings.tokens {
        source.push_str(&format!(
            "Environment=MANDATE_ORDER_TOKEN_CEILING={value}\n"
        ));
    }
}

fn render_timer(resolved: &ResolvedLoop) -> String {
    let calendars = resolved
        .every
        .on_calendars()
        .into_iter()
        .map(|calendar| format!("OnCalendar={calendar}\n"))
        .collect::<String>();
    format!(
        "{GENERATED_HEADER}[Unit]\nDescription=Ostrom loop {} schedule\n\n[Timer]\n{calendars}Persistent=true\nUnit={UNIT_PREFIX}{}.service\n\n[Install]\nWantedBy=timers.target\n",
        resolved.name, resolved.name
    )
}

fn render_number(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{value:.0}")
    } else {
        value.to_string()
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use ostrom_core::PolicyManifest;
    use tempfile::tempdir;

    use super::{
        RECONCILER_UNIT, check_loop_units_drift, generate_loop_units, loop_execstart_is_not_shell,
        render_loop_units,
    };

    const POLICY: &str = r#"manifest_version: 1
defaults:
  loop: {concurrent: 6, spend_usd: 50, tokens: 200000}
actors: {builder: {}}
operations: {work: {steps: []}}
grants:
  builder-work: {actors: builder, operations: work, repositories: placeholder-org/repo}
loops:
  builder-day:
    actor: builder
    operation: work
    target: placeholder-org/repo
    every: 08:15..21:15
  builder-night:
    actor: builder
    operation: work
    target: placeholder-org/repo
    every: ["23:15", "02:15", "05:15"]
    concurrent: 2
"#;

    #[test]
    fn renders_exact_cadence_lines_and_never_a_shell_execstart() {
        let manifest = PolicyManifest::from_yaml(POLICY).expect("manifest");
        let units = generate_loop_units(&manifest).expect("units");
        let day = &units
            .iter()
            .find(|unit| unit.name == "ostrom-loop-builder-day.timer")
            .expect("day timer")
            .contents;
        let night = &units
            .iter()
            .find(|unit| unit.name == "ostrom-loop-builder-night.timer")
            .expect("night timer")
            .contents;
        assert!(day.contains("OnCalendar=*-*-* 08..21:15:00\n"));
        assert!(night.contains("OnCalendar=*-*-* 23,02,05:15:00\n"));
        assert!(loop_execstart_is_not_shell(&units));
        let reconciler = units
            .iter()
            .find(|unit| unit.name == RECONCILER_UNIT)
            .expect("reconciler boot unit");
        assert!(reconciler.contents.contains("ExecStart=ostrom up\n"));
        assert!(!reconciler.contents.contains("systemctl"));
    }

    #[test]
    fn drift_names_missing_changed_and_unexpected_managed_units() {
        let manifest = PolicyManifest::from_yaml(POLICY).expect("manifest");
        let root = tempdir().expect("fixture");
        let written = render_loop_units(&manifest, root.path()).expect("render");
        fs::write(&written[0], "hand edit\n").expect("edit fixture");
        fs::remove_file(&written[1]).expect("remove fixture");
        fs::write(root.path().join("ostrom-loop-stale.timer"), "stale\n")
            .expect("write stale fixture");
        fs::write(root.path().join("unrelated.service"), "unmanaged\n")
            .expect("write unmanaged fixture");

        let drift = check_loop_units_drift(&manifest, root.path()).expect("drift check");
        assert_eq!(drift.changed, ["ostrom-loop-builder-day.service"]);
        assert_eq!(drift.missing, ["ostrom-loop-builder-day.timer"]);
        assert_eq!(drift.unexpected, ["ostrom-loop-stale.timer"]);
    }
}
