//! Ostrom's policy and verdict conversions at the Umwelt runtime boundary.

use std::{
    collections::BTreeMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
    time::{Duration, SystemTime},
};

use chrono::{DateTime, Utc};
use ostrom_core::{
    ActionDefinition, CatalogueEnumeration, CheckContractError, CheckReceipt, CheckVerdict,
    JudgmentClause, PermissionMode, PolicyManifest, ResolvedCheck, ResolvedLoop,
    ResolvedLoopCeilings, RunnerStamp, resolve_check, select_check,
};
use serde::Deserialize;
use serde_json::{Value, json};
use thiserror::Error;
use umwelt_runtime::{
    CeilingEnvironmentNames, CheckAction, CommandProvider, HarnessProfile, LoopUnit,
    LoopUnitDeclaration, LoopUnitDrift, LoopUnitGeneratorConfig, OperationSettingsDrift,
    ResolvedOperationSettings,
};

use crate::{
    DoctorProvider, GitHubProvider, HarnessRequest, HttpProvider, JudgmentHarness, JudgmentOutcome,
};

const GENERATED_HEADER: &str = "# Generated by `ostrom loops render`; do not edit.\n";
const UNIT_PREFIX: &str = "ostrom-loop-";
const RECONCILER_SERVICE: &str = "ostrom-up.service";
const RECONCILER_TIMER: &str = "ostrom-up.timer";

/// Ostrom's judgment protocol over Umwelt's shared harness identity.
pub struct ClaudeJudgmentHarness {
    executable: PathBuf,
    version: String,
    default_model: String,
}

impl ClaudeJudgmentHarness {
    #[must_use]
    pub fn new(
        executable: impl Into<PathBuf>,
        version: impl Into<String>,
        default_model: impl Into<String>,
    ) -> Self {
        Self {
            executable: executable.into(),
            version: version.into(),
            default_model: default_model.into(),
        }
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct HarnessResponse {
    #[serde(default)]
    verdict: Option<CheckVerdict>,
    #[serde(default)]
    because: Vec<JudgmentClause>,
    #[serde(default)]
    error: Option<String>,
    #[serde(default)]
    detail: Option<String>,
}

impl umwelt_runtime::Harness for ClaudeJudgmentHarness {
    fn name(&self) -> &'static str {
        "claude"
    }

    fn version(&self) -> &str {
        &self.version
    }

    fn default_model(&self) -> &str {
        &self.default_model
    }

    fn enforceable_caps(&self) -> umwelt_runtime::CapSupport {
        umwelt_runtime::CapSupport::none()
    }
}

impl JudgmentHarness for ClaudeJudgmentHarness {
    fn judge(&self, request: &HarnessRequest<'_>) -> JudgmentOutcome {
        let mut child = match Command::new(&self.executable)
            .env_clear()
            .current_dir(self.executable.parent().unwrap_or_else(|| Path::new("/")))
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
        {
            Ok(child) => child,
            Err(error) => {
                return JudgmentOutcome::Error(umwelt_runtime::ActionFault::new(
                    "harness_unavailable",
                    Some(error.to_string()),
                ));
            }
        };
        let bytes = serde_json::to_vec(request).expect("harness request serializes");
        if child
            .stdin
            .take()
            .is_none_or(|mut input| input.write_all(&bytes).is_err())
        {
            return JudgmentOutcome::Error(umwelt_runtime::ActionFault::new("harness_io", None));
        }
        let output = match child.wait_with_output() {
            Ok(output) => output,
            Err(error) => {
                return JudgmentOutcome::Error(umwelt_runtime::ActionFault::new(
                    "harness_io",
                    Some(error.to_string()),
                ));
            }
        };
        if !output.status.success() {
            return JudgmentOutcome::Error(umwelt_runtime::ActionFault::new(
                "harness_error",
                Some(String::from_utf8_lossy(&output.stderr).trim().to_owned()),
            ));
        }
        let response: HarnessResponse = match serde_json::from_slice(&output.stdout) {
            Ok(response) => response,
            Err(error) => {
                return JudgmentOutcome::Error(umwelt_runtime::ActionFault::new(
                    "harness_protocol",
                    Some(error.to_string()),
                ));
            }
        };
        match (response.verdict, response.error) {
            (Some(verdict), None) if response.detail.is_none() => JudgmentOutcome::Verdict {
                verdict,
                because: response.because,
            },
            (None, Some(error)) if response.because.is_empty() && !error.is_empty() => {
                JudgmentOutcome::Error(umwelt_runtime::ActionFault::new(
                    "cannot_determine",
                    response.detail.or(Some(error)),
                ))
            }
            _ => JudgmentOutcome::Error(umwelt_runtime::ActionFault::new("harness_protocol", None)),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ActionOutcome {
    Pass,
    Fail,
    Inconclusive(umwelt_runtime::ActionFault),
}

pub trait PreparedAction: Send {
    fn execute(&self) -> ActionOutcome;
}

/// Registration stays in Ostrom because it resolves catalogue meaning and
/// maps observations to verdicts. Providers prepare only bounded work.
pub trait ActionProvider: Send + Sync {
    fn domain(&self) -> &'static str;
    fn verbs(&self) -> &'static [&'static str];
    fn action_definition(&self, verb: &str) -> Option<ActionDefinition>;
    fn prepare(
        &self,
        verb: &str,
        parameters: &BTreeMap<String, Value>,
    ) -> Result<Box<dyn PreparedAction>, umwelt_runtime::ActionFault>;
}

#[derive(Default)]
pub struct ActionRegistry {
    providers: BTreeMap<&'static str, Box<dyn ActionProvider>>,
}

impl ActionRegistry {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    pub fn core(
        plugin_root: impl Into<PathBuf>,
        working_directory: impl Into<PathBuf>,
    ) -> Result<Self, umwelt_runtime::ActionFault> {
        let mut registry = Self::new();
        registry.register(HttpProvider)?;
        registry.register(CommandProvider::default())?;
        registry.register(DoctorProvider::from_environment(plugin_root))?;
        registry.register(GitHubProvider::new(working_directory))?;
        Ok(registry)
    }

    pub fn register(
        &mut self,
        provider: impl ActionProvider + 'static,
    ) -> Result<(), umwelt_runtime::ActionFault> {
        let domain = provider.domain();
        if domain == "agent" {
            return Err(umwelt_runtime::ActionFault::new(
                "judged_domain_registration",
                None,
            ));
        }
        if !valid_component(domain) || provider.verbs().is_empty() {
            return Err(umwelt_runtime::ActionFault::new(
                "invalid_provider_registration",
                None,
            ));
        }
        if self.providers.contains_key(domain) {
            return Err(umwelt_runtime::ActionFault::new("ambiguous_domain", None));
        }

        let mut seen = BTreeMap::new();
        for verb in provider.verbs() {
            if !valid_component(verb) || seen.insert(*verb, ()).is_some() {
                return Err(umwelt_runtime::ActionFault::new(
                    "invalid_provider_registration",
                    None,
                ));
            }
            let Some(action) = provider.action_definition(verb) else {
                return Err(umwelt_runtime::ActionFault::new(
                    "invalid_provider_registration",
                    None,
                ));
            };
            if action.uses != format!("{domain}/{verb}")
                || action.producer.is_empty()
                || action.source_revision.is_empty()
                || action.default_fresh_for_seconds == 0
            {
                return Err(umwelt_runtime::ActionFault::new(
                    "invalid_provider_registration",
                    None,
                ));
            }
        }
        self.providers.insert(domain, Box::new(provider));
        Ok(())
    }

    pub fn prepare(
        &self,
        id: &str,
        enumeration: &CatalogueEnumeration,
    ) -> Result<PreparedCheck, umwelt_runtime::ActionFault> {
        let definition = select_check(id, enumeration).map_err(contract_fault)?;
        let (domain, verb) = exact_action(&definition.uses)?;
        let provider = self
            .providers
            .get(domain)
            .ok_or_else(|| umwelt_runtime::ActionFault::new("unregistered_action", None))?;
        if !provider.verbs().contains(&verb) {
            return Err(umwelt_runtime::ActionFault::new(
                "unregistered_action",
                None,
            ));
        }
        let action_definition = provider
            .action_definition(verb)
            .ok_or_else(|| umwelt_runtime::ActionFault::new("unregistered_action", None))?;
        let action = provider.prepare(verb, &definition.with)?;
        let resolved =
            resolve_check(id, enumeration, &action_definition).map_err(contract_fault)?;
        Ok(PreparedCheck { resolved, action })
    }
}

pub struct PreparedCheck {
    resolved: ResolvedCheck,
    action: Box<dyn PreparedAction>,
}

impl PreparedCheck {
    #[must_use]
    pub fn resolved(&self) -> &ResolvedCheck {
        &self.resolved
    }

    #[must_use]
    pub fn execute(&self, attempt_id: &str) -> CheckReceipt {
        let observed_at = DateTime::<Utc>::from(SystemTime::now());
        self.execute_at(attempt_id, observed_at)
    }

    #[must_use]
    pub fn execute_at(&self, attempt_id: &str, observed_at: DateTime<Utc>) -> CheckReceipt {
        let started = std::time::Instant::now();
        let outcome = self.action.execute();
        let elapsed = chrono::Duration::from_std(started.elapsed()).unwrap_or_default();
        let completed_at = observed_at
            .checked_add_signed(elapsed)
            .unwrap_or(observed_at);
        stamp_outcome(
            &self.resolved,
            attempt_id,
            observed_at,
            completed_at,
            outcome,
        )
    }
}

fn stamp_outcome(
    resolved: &ResolvedCheck,
    attempt_id: &str,
    observed_at: DateTime<Utc>,
    completed_at: DateTime<Utc>,
    outcome: ActionOutcome,
) -> CheckReceipt {
    let stamp = RunnerStamp {
        resolved,
        attempt_id,
        observed_at,
        completed_at,
    };
    match outcome {
        ActionOutcome::Pass => stamp
            .stamp(json!({"result_version": 1, "verdict": "pass"}))
            .expect("built-in pass result is a valid receipt"),
        ActionOutcome::Fail => stamp
            .stamp(json!({"result_version": 1, "verdict": "fail"}))
            .expect("built-in fail result is a valid receipt"),
        ActionOutcome::Inconclusive(_fault) => stamp
            .stamp(json!({"result_version": 1, "verdict": "inconclusive"}))
            .expect("built-in inconclusive result is a valid receipt"),
    }
}

impl ActionProvider for CommandProvider {
    fn domain(&self) -> &'static str {
        "cmd"
    }

    fn verbs(&self) -> &'static [&'static str] {
        &["run"]
    }

    fn action_definition(&self, verb: &str) -> Option<ActionDefinition> {
        command_action_definition(verb)
    }

    fn prepare(
        &self,
        verb: &str,
        parameters: &BTreeMap<String, Value>,
    ) -> Result<Box<dyn PreparedAction>, umwelt_runtime::ActionFault> {
        command_check_action(self, verb, parameters)
            .map(|action| Box::new(RuntimeCommandAction(action)) as Box<dyn PreparedAction>)
    }
}

fn command_action_definition(verb: &str) -> Option<ActionDefinition> {
    (verb == "run").then(|| ActionDefinition {
        uses: "cmd/run".to_owned(),
        producer: "ostrom-cmd".to_owned(),
        default_fresh_for_seconds: 300,
        definition: json!({
            "parameters": ["script", "timeout"],
            "timeout_default": "30s",
            "exit": "zero passes; one fails; any other status is inconclusive"
        }),
        source_revision: "cmd-run-v2".to_owned(),
    })
}

fn command_check_action(
    provider: &CommandProvider,
    verb: &str,
    parameters: &BTreeMap<String, Value>,
) -> Result<CheckAction, umwelt_runtime::ActionFault> {
    if verb != "run" || !exact_keys(parameters, &["script", "timeout"]) {
        return Err(invalid_parameters());
    }
    let script = parameters
        .get("script")
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(invalid_parameters)?;
    let timeout = parameter_timeout(parameters.get("timeout"))?;
    provider.prepare(script, timeout)
}

struct RuntimeCommandAction(CheckAction);

impl PreparedAction for RuntimeCommandAction {
    fn execute(&self) -> ActionOutcome {
        classify_command_receipt(&umwelt_runtime::execute_check_action(&self.0))
    }
}

fn classify_command_receipt(receipt: &umwelt_runtime::CheckReceipt) -> ActionOutcome {
    if let Some(fault) = &receipt.fault {
        let name = if fault.name() == "check_timed_out" {
            "cmd_timeout"
        } else {
            "cmd_execute_error"
        };
        return ActionOutcome::Inconclusive(umwelt_runtime::ActionFault::new(name, None));
    }
    let Some(status) = receipt.status else {
        return ActionOutcome::Inconclusive(umwelt_runtime::ActionFault::new(
            "cmd_execute_error",
            None,
        ));
    };
    if status.success() {
        ActionOutcome::Pass
    } else if status.code() == Some(1) && !interpreter_crashed(&receipt.stderr) {
        ActionOutcome::Fail
    } else {
        ActionOutcome::Inconclusive(umwelt_runtime::ActionFault::new("cmd_harness_error", None))
    }
}

fn interpreter_crashed(stderr: &[u8]) -> bool {
    let stderr = String::from_utf8_lossy(stderr);
    stderr.contains("SyntaxError") || stderr.contains("Traceback (most recent call last):")
}

pub(crate) fn parameter_timeout(
    value: Option<&Value>,
) -> Result<Duration, umwelt_runtime::ActionFault> {
    let milliseconds = match value {
        None => 30_000,
        Some(Value::Number(number)) => number
            .as_u64()
            .and_then(|seconds| seconds.checked_mul(1_000))
            .ok_or_else(invalid_parameters)?,
        Some(Value::String(value)) => parse_duration(value)?,
        Some(_) => return Err(invalid_parameters()),
    };
    if milliseconds == 0 {
        return Err(invalid_parameters());
    }
    Ok(Duration::from_millis(milliseconds))
}

fn parse_duration(value: &str) -> Result<u64, umwelt_runtime::ActionFault> {
    let split = value
        .find(|character: char| !character.is_ascii_digit())
        .ok_or_else(invalid_parameters)?;
    let (amount, unit) = value.split_at(split);
    let amount = amount.parse::<u64>().map_err(|_| invalid_parameters())?;
    let multiplier = match unit {
        "ms" => 1,
        "s" => 1_000,
        "m" => 60_000,
        _ => return Err(invalid_parameters()),
    };
    amount
        .checked_mul(multiplier)
        .ok_or_else(invalid_parameters)
}

pub(crate) fn invalid_parameters() -> umwelt_runtime::ActionFault {
    umwelt_runtime::process::invalid_parameters()
}

pub(crate) fn exact_keys(parameters: &BTreeMap<String, Value>, allowed: &[&str]) -> bool {
    parameters
        .keys()
        .all(|key| key == "fresh_for" || allowed.contains(&key.as_str()))
}

pub(crate) use umwelt_runtime::process::{ProcessResult, run_bounded};

fn valid_component(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

fn exact_action(uses: &str) -> Result<(&str, &str), umwelt_runtime::ActionFault> {
    let Some((domain, verb)) = uses.split_once('/') else {
        return Err(umwelt_runtime::ActionFault::new(
            "unregistered_action",
            None,
        ));
    };
    if !valid_component(domain) || !valid_component(verb) || verb.contains('/') {
        return Err(umwelt_runtime::ActionFault::new(
            "unregistered_action",
            None,
        ));
    }
    Ok((domain, verb))
}

fn contract_fault(error: CheckContractError) -> umwelt_runtime::ActionFault {
    umwelt_runtime::ActionFault::new(
        error.fault_name().unwrap_or("invalid_check_definition"),
        None,
    )
}

#[derive(Debug, Error)]
pub enum OperationSettingsError {
    #[error("unknown actor `{0}`")]
    UnknownActor(String),
    #[error(transparent)]
    Runtime(#[from] umwelt_runtime::OperationSettingsError),
}

/// Resolve all harness-facing operation settings while policy meaning remains local.
pub fn resolved_operation_settings(
    manifest: &PolicyManifest,
    actor: &str,
    prompt: impl Into<String>,
    ceilings: ResolvedLoopCeilings,
) -> Result<ResolvedOperationSettings, OperationSettingsError> {
    let actor_declaration = manifest
        .actors
        .get(actor)
        .ok_or_else(|| OperationSettingsError::UnknownActor(actor.to_owned()))?;
    let allow = manifest
        .operations
        .keys()
        .filter(|operation| actor_has_grant(manifest, actor, operation))
        .map(|operation| format!("Bash(ostrom {operation} *)"))
        .collect();
    Ok(ResolvedOperationSettings {
        prompt: prompt.into(),
        permission_mode: match actor_declaration.permission_mode {
            PermissionMode::Auto => "auto",
            PermissionMode::Manual => "manual",
        }
        .to_owned(),
        profile: HarnessProfile {
            environment: BTreeMap::from([("OSTROM_ACTOR".to_owned(), actor.to_owned())]),
            default_mode: "deny".to_owned(),
            allow,
        },
        ceilings: ostrom_store::umwelt_edge::run_ceilings(ceilings),
    })
}

pub fn generate_operation_settings(
    manifest: &PolicyManifest,
    actor: &str,
) -> Result<String, OperationSettingsError> {
    let settings = resolved_operation_settings(manifest, actor, String::new(), Default::default())?;
    umwelt_runtime::generate_operation_settings(&settings).map_err(Into::into)
}

pub fn check_operation_settings_drift(
    manifest: &PolicyManifest,
    actor: &str,
    path: &Path,
) -> Result<Option<OperationSettingsDrift>, OperationSettingsError> {
    let settings = resolved_operation_settings(manifest, actor, String::new(), Default::default())?;
    let drift = umwelt_runtime::check_operation_settings_drift(&settings, path)?;
    Ok(drift.map(|mut drift| {
        drift.detail = format!(
            "{} differs from settings derived for actor `{actor}`",
            path.display()
        );
        drift
    }))
}

fn actor_has_grant(manifest: &PolicyManifest, actor: &str, operation: &str) -> bool {
    manifest.grants.values().any(|grant| {
        (grant.actors.is_empty() || grant.actors.iter().any(|candidate| candidate == actor))
            && (grant.operations.is_empty()
                || grant
                    .operations
                    .iter()
                    .any(|candidate| candidate == operation))
    })
}

#[derive(Debug, Error)]
pub enum LoopUnitError {
    #[error("could not resolve loop `{name}`: {message}")]
    Resolve { name: String, message: String },
    #[error(transparent)]
    Runtime(#[from] umwelt_runtime::LoopUnitError),
}

fn loop_unit_config() -> LoopUnitGeneratorConfig {
    LoopUnitGeneratorConfig {
        generated_header: GENERATED_HEADER.to_owned(),
        unit_prefix: UNIT_PREFIX.to_owned(),
        externally_managed: vec![RECONCILER_SERVICE.to_owned(), RECONCILER_TIMER.to_owned()],
    }
}

fn loop_unit_declarations(
    manifest: &PolicyManifest,
) -> Result<Vec<LoopUnitDeclaration>, LoopUnitError> {
    manifest
        .loops
        .keys()
        .map(|name| {
            manifest
                .resolve_loop(name)
                .map_err(|error| LoopUnitError::Resolve {
                    name: name.clone(),
                    message: error.to_string(),
                })
                .map(|resolved| loop_unit_declaration(&resolved))
        })
        .collect()
}

fn loop_unit_declaration(resolved: &ResolvedLoop) -> LoopUnitDeclaration {
    LoopUnitDeclaration {
        name: resolved.name.clone(),
        description: format!("Ostrom loop {}", resolved.name),
        argv: vec![
            "ostrom".to_owned(),
            "loop".to_owned(),
            "run".to_owned(),
            resolved.name.clone(),
        ],
        on_calendars: resolved.every.on_calendars(),
        environment: BTreeMap::from([("OSTROM_ACTOR".to_owned(), resolved.actor.clone())]),
        ceiling_environment: CeilingEnvironmentNames {
            concurrent: Some("MANDATE_MAX_IMPLEMENTERS".to_owned()),
            spend_usd: Some("MANDATE_DAILY_CAP_USD".to_owned()),
            tokens: Some("MANDATE_ORDER_TOKEN_CEILING".to_owned()),
        },
        ceilings: ostrom_store::umwelt_edge::run_ceilings(resolved.ceilings),
    }
}

pub fn generate_loop_units(manifest: &PolicyManifest) -> Result<Vec<LoopUnit>, LoopUnitError> {
    let declarations = loop_unit_declarations(manifest)?;
    let mut units = umwelt_runtime::generate_loop_units(&loop_unit_config(), &declarations)?;
    if !declarations.is_empty() {
        units.extend(reconciler_units());
    }
    units.sort_by(|left, right| left.name.cmp(&right.name));
    Ok(units)
}

/// Write generated units without enabling, starting, or reloading them.
pub fn render_loop_units(
    manifest: &PolicyManifest,
    output: &Path,
) -> Result<Vec<PathBuf>, LoopUnitError> {
    let declarations = loop_unit_declarations(manifest)?;
    let mut written =
        umwelt_runtime::render_loop_units(&loop_unit_config(), &declarations, output)?;
    if !declarations.is_empty() {
        for unit in reconciler_units() {
            let path = output.join(unit.name);
            fs::write(&path, unit.contents).map_err(|source| {
                LoopUnitError::Runtime(umwelt_runtime::LoopUnitError::Write {
                    path: path.clone(),
                    source,
                })
            })?;
            written.push(path);
        }
    }
    written.sort();
    Ok(written)
}

pub fn check_loop_units_drift(
    manifest: &PolicyManifest,
    installed: &Path,
) -> Result<LoopUnitDrift, LoopUnitError> {
    let declarations = loop_unit_declarations(manifest)?;
    let mut drift =
        umwelt_runtime::check_loop_units_drift(&loop_unit_config(), &declarations, installed)?;
    for unit in reconciler_units() {
        let path = installed.join(&unit.name);
        if declarations.is_empty() {
            if path.exists() {
                drift.unexpected.push(unit.name);
            }
        } else if !path.exists() {
            drift.missing.push(unit.name);
        } else {
            let actual = fs::read_to_string(&path).map_err(|source| {
                LoopUnitError::Runtime(umwelt_runtime::LoopUnitError::Read { path, source })
            })?;
            if actual != unit.contents {
                drift.changed.push(unit.name);
            }
        }
    }
    drift.missing.sort();
    drift.changed.sort();
    drift.unexpected.sort();
    Ok(drift)
}

#[must_use]
pub fn loop_execstart_is_not_shell(units: &[LoopUnit]) -> bool {
    umwelt_runtime::loop_execstart_is_not_shell(&loop_unit_config(), units)
}

fn reconciler_units() -> [LoopUnit; 2] {
    [
        LoopUnit {
            name: RECONCILER_SERVICE.to_owned(),
            contents: concat!(
                "# Generated by `ostrom loops render`; do not edit.\n",
                "[Unit]\n",
                "Description=Reconcile Ostrom loops from the current policy version\n",
                "Wants=network-online.target\n",
                "After=network-online.target\n\n",
                "[Service]\n",
                "Type=oneshot\n",
                "ExecStart=ostrom up\n\n",
                "[Install]\n",
                "WantedBy=default.target\n",
            )
            .to_owned(),
        },
        LoopUnit {
            name: RECONCILER_TIMER.to_owned(),
            contents: concat!(
                "# Generated by `ostrom loops render`; do not edit.\n",
                "[Unit]\n",
                "Description=Periodically reconcile Ostrom loops from the current policy version\n\n",
                "[Timer]\n",
                "OnBootSec=1min\n",
                "OnUnitActiveSec=5min\n",
                "AccuracySec=1min\n",
                "Unit=ostrom-up.service\n\n",
                "[Install]\n",
                "WantedBy=timers.target\n",
            )
            .to_owned(),
        },
    ]
}

#[cfg(test)]
mod tests {
    use std::{collections::BTreeMap, fs};

    use ostrom_core::{
        Catalogue, CatalogueEnumeration, CheckDocument, CheckVerdict, PolicyManifest,
        ResolvedLoopCeilings,
    };
    use serde_json::json;
    use tempfile::tempdir;

    use super::*;

    const POLICY: &str = "manifest_version: 1\nactors: {builder: {}, gatekeeper: {permission_mode: manual}}\noperations:\n  comment:\n    steps:\n      - uses: gh/post-verdict\n        with: {note: placeholder}\n  merge:\n    steps:\n      - uses: gh/merge-pr\n        requires: ready\ngrants:\n  builder-comment: {actors: builder, operations: comment}\n  gatekeeper-merge: {actors: gatekeeper, operations: merge}\n";

    fn command_catalogue(script: &str) -> CatalogueEnumeration {
        let yaml = format!(
            "checks_version: 1\nchecks:\n  command:\n    uses: cmd/run\n    with:\n      script: {script:?}\n      timeout: 1s\n"
        );
        CatalogueEnumeration {
            catalogues: vec![Catalogue {
                document: CheckDocument::from_yaml(&yaml).expect("command fixture"),
            }],
            complete: true,
        }
    }

    #[test]
    fn action_definition_resolves_to_the_same_umwelt_check_action() {
        let definition = command_action_definition("run").expect("command definition");
        let parameters = BTreeMap::from([
            ("script".to_owned(), json!("exit 0")),
            ("timeout".to_owned(), json!("2s")),
        ]);
        let action = command_check_action(&CommandProvider::default(), "run", &parameters)
            .expect("runtime action");

        assert_eq!(definition.uses, "cmd/run");
        assert_eq!(definition.producer, "ostrom-cmd");
        assert_eq!(action.command, PathBuf::from("sh"));
        assert_eq!(action.arguments, ["-c", "exit 0"]);
        assert_eq!(action.timeout, Duration::from_secs(2));
    }

    #[test]
    fn umwelt_receipt_classification_and_ostrom_stamping_agree() {
        let mut registry = ActionRegistry::new();
        registry
            .register(CommandProvider::default())
            .expect("command provider");

        for (script, expected) in [
            ("exit 0", CheckVerdict::Pass),
            ("exit 1", CheckVerdict::Fail),
            ("exit 7", CheckVerdict::Inconclusive),
        ] {
            let receipt = registry
                .prepare("command", &command_catalogue(script))
                .expect("prepared command")
                .execute("command-attempt");
            assert_eq!(receipt.verdict, Some(expected));
            assert_eq!(receipt.error, None);
        }
    }

    #[test]
    fn policy_settings_resolve_to_the_umwelt_profile_without_drift() {
        let manifest = PolicyManifest::from_yaml(POLICY).expect("manifest");
        let resolved = resolved_operation_settings(
            &manifest,
            "builder",
            "Resolve the selected operation.",
            ResolvedLoopCeilings {
                concurrent: Some(2),
                spend_usd: Some(50.0),
                tokens: Some(200_000),
            },
        )
        .expect("resolved settings");

        assert_eq!(resolved.prompt, "Resolve the selected operation.");
        assert_eq!(resolved.permission_mode, "auto");
        assert_eq!(resolved.profile.default_mode, "deny");
        assert_eq!(resolved.profile.environment["OSTROM_ACTOR"], "builder");
        assert_eq!(resolved.profile.allow, ["Bash(ostrom comment *)"]);
        assert_eq!(resolved.ceilings.concurrent, Some(2));

        let rendered = generate_operation_settings(&manifest, "builder").expect("settings");
        assert_eq!(
            rendered,
            concat!(
                "{\n",
                "  \"$schema\": \"https://json.schemastore.org/claude-code-settings.json\",\n",
                "  \"env\": {\n",
                "    \"OSTROM_ACTOR\": \"builder\"\n",
                "  },\n",
                "  \"permissions\": {\n",
                "    \"defaultMode\": \"deny\",\n",
                "    \"allow\": [\n",
                "      \"Bash(ostrom comment *)\"\n",
                "    ]\n",
                "  }\n",
                "}\n",
            )
        );
    }

    #[test]
    fn loop_resolution_agrees_with_umwelt_and_committed_bytes() {
        let source = include_str!("../../ostrom-cli/tests/fixtures/loops/policy.yaml");
        let manifest = PolicyManifest::from_yaml(source).expect("loop manifest");
        let declarations = loop_unit_declarations(&manifest).expect("loop declarations");
        let builder = declarations
            .iter()
            .find(|declaration| declaration.name == "builder-day")
            .expect("builder-day declaration");
        assert_eq!(builder.description, "Ostrom loop builder-day");
        assert_eq!(builder.argv, ["ostrom", "loop", "run", "builder-day"]);
        assert_eq!(builder.environment["OSTROM_ACTOR"], "builder");

        for unit in generate_loop_units(&manifest).expect("generated units") {
            let expected = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../ostrom-cli/tests/fixtures/loops/expected")
                .join(&unit.name);
            assert_eq!(
                unit.contents.as_bytes(),
                fs::read(expected).expect("golden")
            );
        }
    }

    #[test]
    fn reconciler_units_match_issue_487_goldens_byte_for_byte() {
        let [service, timer] = reconciler_units();
        assert_eq!(
            service.contents,
            concat!(
                "# Generated by `ostrom loops render`; do not edit.\n",
                "[Unit]\n",
                "Description=Reconcile Ostrom loops from the current policy version\n",
                "Wants=network-online.target\n",
                "After=network-online.target\n\n",
                "[Service]\n",
                "Type=oneshot\n",
                "ExecStart=ostrom up\n\n",
                "[Install]\n",
                "WantedBy=default.target\n",
            )
        );
        assert_eq!(
            timer.contents,
            concat!(
                "# Generated by `ostrom loops render`; do not edit.\n",
                "[Unit]\n",
                "Description=Periodically reconcile Ostrom loops from the current policy version\n\n",
                "[Timer]\n",
                "OnBootSec=1min\n",
                "OnUnitActiveSec=5min\n",
                "AccuracySec=1min\n",
                "Unit=ostrom-up.service\n\n",
                "[Install]\n",
                "WantedBy=timers.target\n",
            )
        );
    }

    #[test]
    fn reconciler_drift_remains_owned_by_ostrom() {
        let manifest = PolicyManifest::from_yaml(
            "manifest_version: 1\nactors: {builder: {}}\noperations: {work: {steps: []}}\ngrants: {work: {actors: builder, operations: work}}\nloops:\n  builder:\n    actor: builder\n    operation: work\n    target: placeholder/repo\n    every: hourly\n",
        )
        .expect("manifest");
        let root = tempdir().expect("fixture");
        render_loop_units(&manifest, root.path()).expect("render units");
        fs::write(root.path().join(RECONCILER_SERVICE), "hand edit\n").expect("edit service");

        let drift = check_loop_units_drift(&manifest, root.path()).expect("check drift");
        assert_eq!(drift.changed, [RECONCILER_SERVICE]);
    }
}
